version: "3.9"

services:
  db:
    image: postgres:15
    container_name: primerice-db
    restart: always
    environment:
      POSTGRES_USER: primerice
      POSTGRES_PASSWORD: primerice
      POSTGRES_DB: primerice
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

