apiVersion: v1
kind: Secret
metadata:
  name: primerice-secrets
  namespace: primerice
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@primerice-postgres:5432/primerice
  POSTGRES_PASSWORD: postgres
  JWT_SECRET: supersecretkey

